import { cn } from "../classnames";

const inputBase = cn(
  "w-full min-h-[2.55rem] rounded-[0.52rem] border",
  "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
  "bg-[var(--field-bg)] px-[0.74rem] py-[0.64rem]",
  "text-base text-[var(--text)] outline-none",
  "focus:border-[color:color-mix(in_srgb,var(--text)_24%,transparent)]",
  "focus:shadow-[0_0_0_3px_var(--focus-ring)]",
  "min-[620px]:text-[0.9rem]",
);

const iconButtonBase = cn(
  "inline-flex h-[2.05rem] w-[2.05rem] cursor-pointer items-center justify-center rounded-[0.45rem] border",
  "border-[color:color-mix(in_srgb,var(--text)_10%,transparent)]",
  "bg-[var(--bg)] text-[var(--muted)] [touch-action:manipulation]",
  "disabled:cursor-not-allowed disabled:opacity-[0.35]",
  "hover:enabled:border-[color:color-mix(in_srgb,var(--text)_20%,transparent)]",
  "hover:enabled:text-[var(--text)]",
);

export const styles = {
  loggerShell: cn(
    "flex min-h-dvh justify-center px-[0.95rem] pt-[0.95rem]",
    "pb-[calc(0.95rem+env(safe-area-inset-bottom))]",
    "min-[620px]:p-[1.4rem]",
  ),
  loggerStage: cn(
    "flex w-full max-w-[36rem] flex-col gap-[0.72rem]",
    "min-[620px]:max-w-[50rem]",
  ),
  topRow: "flex items-center justify-between gap-[0.5rem]",
  backLink: cn(
    "inline-flex min-h-[2rem] cursor-pointer items-center justify-center gap-[0.35rem] whitespace-nowrap rounded-full border",
    "border-[color:color-mix(in_srgb,var(--text)_14%,transparent)]",
    "bg-[var(--bg)] px-[0.72rem] text-[0.76rem] text-[var(--text)] [touch-action:manipulation]",
    "hover:border-[color:color-mix(in_srgb,var(--text)_22%,transparent)]",
  ),
  backButtonIcon: "h-[0.88rem] w-[0.88rem] shrink-0 stroke-current",
  header: "flex flex-col gap-[0.28rem]",
  headerEyebrow:
    "m-0 text-xs font-semibold text-[var(--muted)]",
  titleRow: "flex min-w-0 items-start justify-between gap-[0.5rem]",
  titleActions: "inline-flex shrink-0 items-center gap-[0.35rem]",
  headerIconButton: iconButtonBase,
  title:
    "m-0 min-w-0 flex-1 text-[clamp(1.8rem,7vw,2.35rem)] leading-[1.02] tracking-[-0.02em] font-[560]",
  autosaveMeta: "m-0 text-[0.74rem] tracking-[0.02em] text-[var(--muted)]",
  form: "flex flex-col gap-[0.62rem] p-[2px]",
  card: cn(
    "flex flex-col gap-[0.6rem] rounded-[0.72rem] border bg-[var(--bg)] p-[0.78rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
  ),
  metaGrid: "grid gap-[0.55rem] min-[620px]:grid-cols-2",
  field: "flex flex-col gap-[0.22rem]",
  fieldInputRow: "flex items-stretch gap-[0.55rem]",
  fieldActionButton: cn(
    iconButtonBase,
    "!h-auto !w-auto shrink-0 self-stretch aspect-square rounded-[0.52rem]",
  ),
  confirmOverlay: cn(
    "fixed inset-0 z-[80] flex items-end justify-center",
    "bg-[color:color-mix(in_srgb,#000_36%,transparent)] px-[0.78rem] pt-[0.78rem]",
    "pb-[calc(0.78rem+env(safe-area-inset-bottom))]",
    "min-[620px]:items-center min-[620px]:p-[1rem]",
  ),
  confirmDialog: cn(
    "flex w-full max-w-[26rem] flex-col gap-[0.62rem] rounded-[0.82rem] border bg-[var(--bg)] p-[0.82rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "shadow-[0_18px_44px_color-mix(in_srgb,#000_24%,transparent)]",
  ),
  confirmEyebrow:
    "m-0 text-[0.72rem] uppercase tracking-[0.08em] text-[var(--muted)]",
  confirmTitle:
    "m-0 text-[1rem] leading-[1.15] tracking-[-0.015em] font-[560] text-[var(--text)]",
  confirmBody:
    "m-0 text-[0.84rem] leading-[1.45] text-[color:color-mix(in_srgb,var(--text)_92%,var(--muted))]",
  confirmActions:
    "flex flex-col gap-[0.5rem] pt-[0.1rem] min-[620px]:flex-row min-[620px]:justify-end",
  confirmSecondaryButton: cn(
    "inline-flex min-h-[2.75rem] items-center justify-center rounded-[0.56rem] border bg-[var(--bg)] px-[0.9rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "text-[0.84rem] text-[var(--text)] [touch-action:manipulation]",
    "hover:border-[color:color-mix(in_srgb,var(--text)_20%,transparent)]",
    "disabled:cursor-not-allowed disabled:opacity-[0.45]",
    "min-[620px]:min-w-[9.5rem]",
  ),
  confirmPrimaryButton: cn(
    "inline-flex min-h-[2.75rem] items-center justify-center rounded-[0.56rem] border px-[0.9rem]",
    "border-[color:color-mix(in_srgb,#b13d48_34%,transparent)]",
    "bg-[color:color-mix(in_srgb,#b13d48_10%,var(--bg))]",
    "text-[0.84rem] text-[#b13d48] [touch-action:manipulation]",
    "hover:border-[color:color-mix(in_srgb,#b13d48_46%,transparent)]",
    "hover:bg-[color:color-mix(in_srgb,#b13d48_14%,var(--bg))]",
    "disabled:cursor-not-allowed disabled:opacity-[0.45]",
    "min-[620px]:min-w-[9.5rem]",
  ),
  label: "text-[0.68rem] text-[var(--muted)]",
  input: inputBase,
  datePickerWrapper:
    "w-full [&_.react-datepicker__input-container]:block [&_.react-datepicker__input-container]:w-full",
  datePickerCalendar: "",
  dateInput: "w-full [font-variant-numeric:tabular-nums] tracking-[0.01em]",
  datePickerPopper: cn(
    "z-[60]",
    "[&_.react-datepicker]:overflow-hidden [&_.react-datepicker]:rounded-[0.82rem]",
    "[&_.react-datepicker]:border [&_.react-datepicker]:border-[color:color-mix(in_srgb,var(--text)_14%,transparent)]",
    "[&_.react-datepicker]:bg-[var(--bg)] [&_.react-datepicker]:text-[var(--text)]",
    "[&_.react-datepicker]:shadow-[0_16px_30px_color-mix(in_srgb,#000_28%,transparent)]",
    "[&_.react-datepicker__header]:border-b",
    "[&_.react-datepicker__header]:border-[color:color-mix(in_srgb,var(--text)_10%,transparent)]",
    "[&_.react-datepicker__header]:bg-[var(--bg)] [&_.react-datepicker__header]:pt-[0.56rem]",
    "[&_.react-datepicker__current-month]:text-[0.9rem]",
    "[&_.react-datepicker__current-month]:tracking-[-0.01em]",
    "[&_.react-datepicker__current-month]:text-[var(--text)]",
    "[&_.react-datepicker__current-month]:font-[560]",
    "[&_.react-datepicker__day-names]:mt-[0.35rem]",
    "[&_.react-datepicker__day-name]:w-[2rem] [&_.react-datepicker__day-name]:leading-[2rem]",
    "[&_.react-datepicker__day-name]:text-[0.7rem] [&_.react-datepicker__day-name]:text-[var(--muted)]",
    "[&_.react-datepicker__month]:mx-[0.5rem] [&_.react-datepicker__month]:mb-[0.5rem]",
    "[&_.react-datepicker__month]:mt-[0.42rem]",
    "[&_.react-datepicker__day]:m-[0.12rem] [&_.react-datepicker__day]:w-[2rem]",
    "[&_.react-datepicker__day]:rounded-[0.5rem] [&_.react-datepicker__day]:leading-[2rem]",
    "[&_.react-datepicker__day]:text-[color:color-mix(in_srgb,var(--text)_90%,var(--muted))]",
    "[&_.react-datepicker__day]:transition-colors",
    "[&_.react-datepicker__day:hover]:bg-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "[&_.react-datepicker__day:hover]:text-[var(--text)]",
    "[&_.react-datepicker__day--today]:font-[560]",
    "[&_.react-datepicker__day--today]:shadow-[inset_0_0_0_1px_color-mix(in_srgb,var(--text)_20%,transparent)]",
    "[&_.react-datepicker__day--selected]:bg-[color:color-mix(in_srgb,var(--text)_84%,var(--bg))]",
    "[&_.react-datepicker__day--selected]:text-[var(--bg)]",
    "[&_.react-datepicker__day--keyboard-selected]:bg-[color:color-mix(in_srgb,var(--text)_84%,var(--bg))]",
    "[&_.react-datepicker__day--keyboard-selected]:text-[var(--bg)]",
    "[&_.react-datepicker__navigation]:top-[0.58rem]",
    "[&_.react-datepicker__navigation-icon::before]:border-[var(--muted)]",
  ),
  exerciseSection: "flex flex-col gap-[0.62rem]",
  exerciseCard: cn(
    "flex flex-col gap-[0.58rem] rounded-[0.72rem] border bg-[var(--bg)] p-[0.78rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "transition-[border-color,background-color,transform,box-shadow]",
  ),
  exerciseCardDragging: cn(
    "border-[color:color-mix(in_srgb,var(--text)_18%,transparent)]",
    "bg-[var(--bg)] [box-shadow:0_12px_24px_color-mix(in_srgb,#000_14%,transparent)]",
    "scale-[0.99]",
  ),
  exerciseCardDropTarget: cn(
    "border-[color:color-mix(in_srgb,var(--text)_28%,transparent)]",
    "bg-[var(--bg)]",
  ),
  exerciseHead: "flex items-center justify-between gap-[0.55rem]",
  exerciseHeading: "flex min-w-0 flex-1 items-center gap-[0.48rem]",
  exerciseNameInput: "min-h-[2.05rem] h-[2.05rem] min-w-0 flex-1 rounded-[0.45rem] px-[0.74rem]",
  exerciseTitle: "",
  exerciseMeta: "mt-[0.12rem] text-[0.72rem] text-[var(--muted)]",
  iconButton: iconButtonBase,
  dragHandle: "shrink-0 cursor-grab [touch-action:none] active:cursor-grabbing",
  icon: "h-4 w-4 shrink-0 stroke-current",
  inlineRow: "block",
  searchResults: cn(
    "mt-[0.48rem] flex flex-col gap-[0.45rem] rounded-[0.56rem] border p-[0.52rem]",
    "border-[color:color-mix(in_srgb,var(--text)_10%,transparent)]",
    "bg-[var(--field-bg)]",
  ),
  searchResultsLabel: "m-0 text-[0.7rem] text-[var(--muted)]",
  searchResultsList:
    "flex max-h-[12rem] flex-wrap gap-[0.42rem] overflow-y-auto max-[420px]:max-h-[14rem] max-[420px]:flex-col max-[420px]:flex-nowrap",
  searchResultButton: cn(
    "min-h-[2.4rem] cursor-pointer rounded-full border bg-[var(--bg)] px-[0.78rem] py-[0.45rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "text-left text-[0.86rem] leading-[1.2] text-[var(--text)] [touch-action:manipulation]",
    "hover:border-[color:color-mix(in_srgb,var(--text)_22%,transparent)]",
    "max-[420px]:w-full max-[420px]:rounded-[0.56rem]",
  ),
  compareHint: "mt-[-0.1rem] text-[0.76rem] text-[var(--muted)]",
  compareCard: cn(
    "flex flex-col gap-[0.5rem] rounded-[0.56rem] border bg-[var(--bg)] p-[0.62rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
  ),
  compareHead: "flex flex-wrap items-baseline justify-start gap-[0.35rem]",
  compareMeta: "m-0 text-[0.72rem] text-[var(--muted)]",
  compareBody: cn(
    "grid items-start gap-[0.7rem]",
    "grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]",
    "max-[420px]:grid-cols-[minmax(0,0.88fr)_minmax(0,1.12fr)]",
    "min-[620px]:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]",
  ),
  compareGrid: "flex flex-col gap-[0.44rem]",
  compareItem: "flex flex-col gap-[0.12rem]",
  compareLabel: "m-0 text-[0.67rem] text-[var(--muted)]",
  compareValue: "m-0 text-[0.88rem] leading-[1.2]",
  compareSnapshot: "flex flex-col gap-[0.4rem]",
  compareSetList: "flex flex-col gap-[0.36rem]",
  compareSetRow: cn(
    "flex flex-col items-start gap-[0.18rem] rounded-[0.56rem] border bg-[var(--bg)] px-[0.58rem] py-[0.46rem]",
    "border-[color:color-mix(in_srgb,var(--text)_10%,transparent)]",
    "max-[420px]:min-h-[3.7rem]",
  ),
  compareSetIndex:
    "m-0 text-[0.78rem] font-[560] tracking-[0.02em] text-[var(--muted)]",
  compareSetValue: "text-left text-[0.82rem] leading-[1.2]",
  compareDelta:
    "m-0 text-[0.77rem] leading-[1.35] text-[color:color-mix(in_srgb,var(--text)_86%,var(--muted))]",
  predictionPanel: cn(
    "grid items-start gap-[0.7rem] border-t pt-[0.55rem]",
    "border-[color:color-mix(in_srgb,var(--text)_8%,transparent)]",
    "grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]",
    "max-[420px]:grid-cols-[minmax(0,0.88fr)_minmax(0,1.12fr)]",
    "min-[620px]:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]",
  ),
  predictionSummary: "flex flex-col gap-[0.55rem]",
  actionButton: cn(
    "inline-flex min-h-[2.55rem] cursor-pointer items-center gap-[0.35rem] rounded-[0.5rem] border bg-[var(--bg)] px-[0.7rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "text-[0.78rem] text-[var(--text)] [touch-action:manipulation]",
    "hover:border-[color:color-mix(in_srgb,var(--text)_20%,transparent)]",
  ),
  actionIcon: "h-[0.88rem] w-[0.88rem] shrink-0 stroke-current",
  spinningIcon: "h-[0.85rem] w-[0.85rem] shrink-0 stroke-current animate-[spin_0.85s_linear_infinite]",
  setsStack: "flex flex-col gap-[0.58rem] overflow-x-visible py-[6px]",
  setRow: cn(
    "grid grid-cols-2 items-start gap-[0.6rem] rounded-[0.72rem] border bg-[var(--bg)] p-[0.72rem]",
    "border-[color:color-mix(in_srgb,var(--text)_10%,transparent)]",
    "min-[620px]:grid-cols-[auto_minmax(4.8rem,0.95fr)_minmax(4.8rem,0.85fr)_auto]",
    "min-[620px]:items-center min-[620px]:gap-[0.5rem]",
    "min-[620px]:rounded-none min-[620px]:border-none min-[620px]:bg-transparent min-[620px]:p-0",
  ),
  setRowHeader: cn(
    "hidden",
    "min-[620px]:grid min-[620px]:grid-cols-[auto_minmax(4.8rem,0.95fr)_minmax(4.8rem,0.85fr)_auto]",
    "min-[620px]:items-center min-[620px]:gap-[0.5rem]",
    "min-[620px]:bg-transparent min-[620px]:px-[0.1rem] min-[620px]:pb-0 min-[620px]:pt-0",
    "min-[620px]:mb-[2px]",
  ),
  setHeadLabel:
    "whitespace-nowrap text-[0.64rem] uppercase tracking-[0.07em] text-[var(--muted)]",
  setNumber: cn(
    "order-1 m-0 text-[0.78rem] font-[560] tracking-[0.02em] text-[var(--muted)]",
    "min-[620px]:min-w-[1.4rem] min-[620px]:text-center",
    "min-[620px]:text-[0.72rem] min-[620px]:font-normal min-[620px]:tracking-[0]",
  ),
  setField: "min-w-0 flex flex-col gap-[0.3rem] min-[620px]:gap-0",
  setFieldWeight: "order-3 min-[620px]:order-2",
  setFieldReps: "order-4 min-[620px]:order-3",
  setFieldLabel:
    "text-[0.64rem] text-[var(--muted)] min-[620px]:hidden",
  setRemoveButton:
    "order-2 !h-[2.55rem] !w-[2.55rem] self-start justify-self-end !rounded-[0.52rem] min-[620px]:order-4",
  setActions: "flex w-full min-[620px]:justify-end [&>button]:w-full",
  secondaryButton: cn(
    "inline-flex min-h-[2.75rem] cursor-pointer items-center justify-center gap-[0.44rem] rounded-[0.56rem] border bg-[var(--bg)] px-[0.85rem]",
    "border-[color:color-mix(in_srgb,var(--text)_12%,transparent)]",
    "text-[0.84rem] text-[var(--text)] [touch-action:manipulation]",
    "hover:border-[color:color-mix(in_srgb,var(--text)_20%,transparent)]",
  ),
  formError: cn(
    "m-0 rounded-[0.56rem] px-[0.7rem] py-[0.62rem] text-[0.82rem]",
    "bg-[color:color-mix(in_srgb,#9e1f1f_12%,var(--field-bg))]",
    "text-[color:color-mix(in_srgb,var(--text)_90%,#9e1f1f)]",
  ),
  saveButton:
    "inline-flex min-h-[2.95rem] w-full cursor-pointer items-center justify-center gap-[0.42rem] rounded-[0.58rem] border-0 bg-[var(--button-bg)] px-[0.95rem] text-[0.92rem] text-[var(--button-text)] [touch-action:manipulation] disabled:cursor-progress disabled:opacity-70",
} as const;
