import { actionQuiet } from "@/app/components/action.styles";
import { dataListStyles } from "@/app/components/data-list.styles";

export const styles = {
  shell: "flex min-h-dvh justify-center bg-[var(--bg)] px-5 pb-10 pt-4 min-[760px]:p-8",
  stage: "flex w-full max-w-[58rem] flex-col gap-4",
  topRow: "flex items-center justify-between gap-3",
  backLink: `${actionQuiet} -ml-4`,
  backButtonIcon: "h-4 w-4 shrink-0 stroke-current",
  summaryCard: "py-3 min-[760px]:py-5",
  title: "m-0 text-[clamp(2rem,7.5vw,2.5rem)] font-[550] leading-[1.1] tracking-[-0.04em]",
  summaryLine: "mb-0 mt-4 text-[0.9375rem] leading-relaxed text-[var(--text)]",
  summaryMeta: "mb-0 mt-1 text-[0.8125rem] leading-relaxed text-[var(--muted)]",
  panel: "rounded-[var(--app-radius)] border border-[color:var(--app-line)] bg-[var(--app-surface-raised)] p-5 min-[760px]:p-6",
  panelGrid: "grid grid-cols-1 gap-4 min-[980px]:grid-cols-2",
  panelTitle: "m-0 text-[1.1875rem] font-[520] tracking-[-0.025em]",
  panelSubtitle: "mb-4 mt-1 text-[0.8125rem] leading-relaxed text-[var(--muted)]",
  chartFrame: "h-[17rem] w-full min-w-0",
  listStack: dataListStyles.list,
  listRow: dataListStyles.row,
  listRowLink: dataListStyles.rowLink,
  listRowMain: dataListStyles.rowMain,
  listRowStats: dataListStyles.rowStats,
  listRowTitle: dataListStyles.rowTitle,
  listRowMeta: dataListStyles.rowMeta,
  listRowValue: dataListStyles.rowValue,
  pagerRow: dataListStyles.pagerRow,
  pagerButton: dataListStyles.pagerButton,
  pagerIcon: dataListStyles.pagerIcon,
  pagerRange: dataListStyles.pagerRange,
  skeletonBlock: "block rounded-md bg-[linear-gradient(90deg,color-mix(in_srgb,var(--text)_7%,transparent),color-mix(in_srgb,var(--text)_15%,transparent),color-mix(in_srgb,var(--text)_7%,transparent))] bg-[length:220%_100%] animate-[dashboard-skeleton_1.25s_ease-in-out_infinite]",
} as const;
