import {
  actionDanger,
  actionIcon,
  actionMenuRow,
  actionMenuRowDanger,
  actionOutline,
  actionQuiet,
} from "@/app/components/action.styles";

export const styles = {
  shell: "flex min-h-dvh justify-center bg-[var(--bg)] px-5 pb-10 pt-4 min-[760px]:p-8",
  stage: "flex w-full max-w-[58rem] flex-col gap-4",
  topRow: "flex items-center justify-between gap-3",
  topLead: "inline-flex items-center gap-2",
  backLink: `${actionQuiet} -ml-4`,
  backButtonIcon: "h-4 w-4 shrink-0 stroke-current",
  actionButton: actionOutline,
  topActions: "inline-flex items-center justify-end gap-2",
  detailActionsGroup: "inline-flex flex-wrap items-center gap-2 max-[759px]:hidden",
  mobileActionMenu: "hidden max-[759px]:inline-flex",
  mobileActionToggle: actionIcon,
  mobileActionDropdown: "z-50 flex w-48 flex-col gap-1 rounded-2xl border border-[color:var(--app-line)] bg-[var(--app-surface-raised)] p-1 outline-none",
  mobileActionMenuItem: actionMenuRow,
  mobileActionDangerItem: actionMenuRowDanger,
  dangerActionButton: actionDanger,
  actionButtonIcon: "h-4 w-4 shrink-0 stroke-current",
  actionButtonLabel: "whitespace-nowrap",
  summaryCard: "py-3 min-[760px]:py-5",
  titleMeta: "m-0 text-[0.8125rem] text-[var(--muted)]",
  exerciseCard: "rounded-[var(--app-radius)] border border-[color:var(--app-line)] bg-[var(--app-surface-raised)] p-5 min-[760px]:p-6",
  title: "m-0 text-[clamp(2rem,7.5vw,2.5rem)] font-[550] leading-[1.1] tracking-[-0.04em]",
  summaryLine: "mb-0 mt-4 text-[0.9375rem] leading-relaxed text-[var(--text)]",
  summaryMeta: "mb-0 mt-1 text-[0.8125rem] leading-relaxed text-[var(--muted)]",
  exerciseList: "flex flex-col gap-3",
  exerciseHead: "flex flex-col gap-1",
  exerciseName: "m-0 text-[1.1875rem] font-[520] leading-tight tracking-[-0.025em]",
  exerciseMeta: "m-0 text-[0.8125rem] leading-relaxed text-[var(--muted)]",
  setList: "mt-4 flex flex-col",
  setRow: "grid grid-cols-[3.4rem_minmax(0,1fr)_auto] items-baseline gap-2 border-t border-[color:var(--app-line)] py-3 first:border-t-0",
  setOrder: "text-[0.8125rem] text-[var(--muted)]",
  setDetail: "min-w-0 text-[0.9375rem] text-[var(--text)] [font-variant-numeric:tabular-nums]",
  setDuration: "whitespace-nowrap text-[0.8125rem] text-[var(--muted)]",
  skeletonBlock: "block rounded-md bg-[linear-gradient(90deg,color-mix(in_srgb,var(--text)_7%,transparent),color-mix(in_srgb,var(--text)_15%,transparent),color-mix(in_srgb,var(--text)_7%,transparent))] bg-[length:220%_100%] animate-[dashboard-skeleton_1.25s_ease-in-out_infinite]",
} as const;
