import {
  DASHBOARD_METRIC_DEFINITIONS_CATEGORY,
  DASHBOARD_METRIC_DEFINITIONS_SUMMARY,
  DASHBOARD_METRIC_DEFINITIONS_TITLE,
  DASHBOARD_METRIC_DEFINITIONS_UPDATED_AT,
} from "./dashboard-metric-definitions-paper";
import {
  RECOMMENDATION_GUARDRAILS_CATEGORY,
  RECOMMENDATION_GUARDRAILS_SUMMARY,
  RECOMMENDATION_GUARDRAILS_TITLE,
  RECOMMENDATION_GUARDRAILS_UPDATED_AT,
} from "./recommendation-guardrails-paper";
import {
  SCORED_HEURISTIC_PREDICTOR_SUMMARY,
  SCORED_HEURISTIC_PREDICTOR_TITLE,
  SCORED_HEURISTIC_PREDICTOR_UPDATED_AT,
} from "./scored-heuristic-predictor-paper";
import {
  SPLIT_CALENDAR_MATH_CATEGORY,
  SPLIT_CALENDAR_MATH_SUMMARY,
  SPLIT_CALENDAR_MATH_TITLE,
  SPLIT_CALENDAR_MATH_UPDATED_AT,
} from "./split-calendar-math-paper";
import {
  TRAINING_RADAR_CATEGORY,
  TRAINING_RADAR_SUMMARY,
  TRAINING_RADAR_TITLE,
  TRAINING_RADAR_UPDATED_AT,
} from "./training-radar-paper";

export const RESEARCH_PAPERS = [
  {
    href: "/research/shp",
    category: "prediction model",
    title: SCORED_HEURISTIC_PREDICTOR_TITLE,
    updatedAt: SCORED_HEURISTIC_PREDICTOR_UPDATED_AT,
    summary: SCORED_HEURISTIC_PREDICTOR_SUMMARY,
  },
  {
    href: "/research/guardrails",
    category: RECOMMENDATION_GUARDRAILS_CATEGORY,
    title: RECOMMENDATION_GUARDRAILS_TITLE,
    updatedAt: RECOMMENDATION_GUARDRAILS_UPDATED_AT,
    summary: RECOMMENDATION_GUARDRAILS_SUMMARY,
  },
  {
    href: "/research/metrics",
    category: DASHBOARD_METRIC_DEFINITIONS_CATEGORY,
    title: DASHBOARD_METRIC_DEFINITIONS_TITLE,
    updatedAt: DASHBOARD_METRIC_DEFINITIONS_UPDATED_AT,
    summary: DASHBOARD_METRIC_DEFINITIONS_SUMMARY,
  },
  {
    href: "/research/training-radar",
    category: TRAINING_RADAR_CATEGORY,
    title: TRAINING_RADAR_TITLE,
    updatedAt: TRAINING_RADAR_UPDATED_AT,
    summary: TRAINING_RADAR_SUMMARY,
  },
  {
    href: "/research/split-calendar",
    category: SPLIT_CALENDAR_MATH_CATEGORY,
    title: SPLIT_CALENDAR_MATH_TITLE,
    updatedAt: SPLIT_CALENDAR_MATH_UPDATED_AT,
    summary: SPLIT_CALENDAR_MATH_SUMMARY,
  },
] as const;
